name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dfang/wx:$(date +%s) --tag dfang/wx:lastet
    - name: Push the Docker image
      run: docker push dfang/wx:latest
