name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dfang/wx:$(date +%s) --tag dfang/wx:latest
    - name: Push the Docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dfang/wx:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
